version: "3"
services:
    frontend:
        build: ui/
        restart: always
        volumes:
            - data-gen:/var/www/html/ui/data-gen
        networks:
            - default
        depends_on:
            - backend
    backend:
        build: generator2/org.getaviz.generator/
        restart: always
        volumes: 
            - data-gen:/var/lib/jetty/data-gen
        networks:
            - default
        depends_on:
            - neo4j
    tests:
        build: integrationtests/
        command: "/bin/wait-for-it.sh neo4j:7687 -s -t 30 -- mvn install"
        networks:
            - default
        depends_on:
            - neo4j
            - frontend
            - backend
    neo4j:
        image: neo4j:3.5.1
        restart: always
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            NEO4J_AUTH: "none"
        networks:
            - default
volumes:
  data-gen:
    
networks:
    default:
        driver: bridge
